theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title: Android App/FrameWork Developer  React Web Developer

# 对你自己的简洁描述
description: 小皇帝篮球智商极高、突破犀利，拥有出色的视野和传球技术，被认为是NBA有史以来最为全能的球员之一

# 你的美照地址
logo: /assets/images/me.jpg

# 你的名字
name: WuBang Lei

# 你的联系方式
phone: 18376621242

# 你的邮箱
email: raywubang@gmail.com

# 你目前的住址
address:  Shenzhen, Guangdong Province , China 

# 你毕业院校
school: Northern University for Nationalities

# 你的专业
profession: Material Forming and Control Engineering

# 你的学位
degree: undergraduate 

# 专业技能
skills：1. Proficient in Java fundamentals and advanced Android technologies 
2. Familiar with Kotlin Android development, proficient in Android JNI technology, and good mastery of H5/React technology 
3. Proficient in using C++and QML basics, proficient in QT application development, proficient in developing in Linux window environment 
4. Familiar with shell spec scripts and proficient in using xftp xshell 
5. Proficient in using Fiddler Postman Charles tool 
6. Proficient in using git svn TortoiseSVN version management tool

# 你获得过的证书或奖励
credential: National Computer Level 2/CET-4/National Basketball Referee Level 2 Certificate/

